name = "txt-udia-ca"
main = "src/index.ts"
compatibility_date = "2022-09-04"

kv_namespaces = [
  { binding = "txtblob", id = "a79031f374b446cbaf25273b0ee54a5a", preview_id = "7bbb5892ea7c4cb58318102811bb8a3d" }
]

[vars]
CF_TURNSTILE_SITE_KEY = "0x4AAAAAAACaLZCIoPI6458r"
